config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ユーザー用　URL/users/sign_in...
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
  }

  # 管理者用　URL/admin/sign_in...
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  namespace :api do
    namespace :v1 do
      resources :crops, only: [:index, :show]
    end
  end

  scope module: :public do
    root to: 'homes#top'
    resources :users, only: [:update] do
      collection do
        get 'mypage/edit' => 'users#edit'
        patch 'close_account'
        get "check_name"
        get "check_email"
        post 'check_user'
      end
    end
    resources :crops do
      collection do
        get "crop_list"
      end
    end
    resources :fields do
      collection do
        get "field_section_list"
      end
    end
    resources :plans do
      collection do
        get "plan_table"
      end
    end
  end

  namespace :admin do
    root to: 'users#index'
    get 'users/show'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :fields, dependent: :destroy
  has_many :plans, dependent: :destroy
  has_many :crops, dependent: :destroy

  # バリデーション
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  # コールバック
  after_create :create_default_field_and_section

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  private

  def create_default_field_and_section
    field = fields.create(name: "畑A", address: "")
    field.field_sections.create(name: "区画A") if field.present?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<% @users.each do |user| %>

    <div class="bg-white my-3 p-4 mx-auto rounded-pill">
      <div class="row">
        <div class="col mx-2 my-auto ">
          <%#= link_to edit_admin_user_path(user) do %>
            <%#= image_tag user.get_profile_image(80, 80), class: "rounded-circle ml-auto d-block" %>
          <%# end %>
        </div>

        <div class="col mx-2 my-auto">
          <div class="row text-center"><%= user.name %></div>
          <div class="row text-center"><%= user.email.truncate(20) %></div>
          <%# if user.is_active? %>
            <div><b><%#= "有効" %></b></div>
          <%# else %>
            <div class="text-secondary"><b><%#= "無効" %></b></div>
          <%# end %>
        </div>

      </div>
    </div>

<% end %>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>