config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ユーザー用　URL/users/sign_in...
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
  }

  # 管理者用　URL/admin/sign_in...
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  namespace :api do
    namespace :v1 do
      resources :crops, only: [:index, :show]
    end
  end

  scope module: :public do
    root to: 'homes#top'
    resources :users, only: [:update] do
      collection do
        get 'mypage/edit' => 'users#edit'
        patch 'close_account'
        get "check_name"
        get "check_email"
        post 'check_user'
      end
    end
    resources :crops do
      collection do
        get "crop_list"
      end
    end
    resources :fields do
      collection do
        get "field_section_list"
      end
    end
    resources :plans do
      collection do
        get "plan_table"
      end
    end
  end

  namespace :admin do
    root to: 'users#index'
    get 'users/show'
  end

end

app/views/layouts/_bottom_navbar.html.erb
<footer class="footer fixed-bottom" style="background-color: #99B264; height: 80px;">
  <div class="container mt-3">
    <nav class="row d-flex justify-content-center">
      <ul class="nav d-flex justify-content-center list-unstyled mt-3">

        <% if user_signed_in? %>

        <li class="nav-item mx-3">
          <%= link_to plans_path, class: "menu-icon" do %>
            <i class="fa-solid fa-wheat-awn fa-xl" style="color: #000;"></i>
            <p class="text-center mt-3 color-black" style="font-size: 10px;">作付計画</p>
          <% end %>
        </li>

        <li class="nav-item mx-3">
          <%= link_to fields_path, class: "menu-icon", 'data-turbolinks': false do %>
            <i class="fa-solid fa-crop fa-xl" style="color: #000;"></i>
            <p class="text-center mt-3 color-black" style="font-size: 10px;">畑管理</p>
          <% end %>
        </li>

        <li class="nav-item mx-3">
          <%= link_to crops_path, class: "menu-icon", 'data-turbolinks': false do %>
            <i class="fa-solid fa-carrot fa-xl" style="color: #000;"></i>
            <p class="text-center mt-3 color-black" style="font-size: 10px;">作物管理</p>
          <% end %>
        </li>

        <% else %>
        <li class="nav-item mx-3">
          <%= link_to root_path, class: "menu-icon" do %>
            <i class="fa-solid fa-house fa-xl" style="color: #000;"></i>
            <p class="text-center mt-3 color-black" style="font-size: 10px;">使い方</p>
          <% end %>
        </li>
        <% end %>

      </ul>

    </nav>
  </div>
</footer>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<%= object.errors.count %>件のエラーが発生しました
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success text-center mx-auto" style="width: 100%;">
    <%= flash[:notice] %><button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger text-center mx-auto" style="width: 100%;">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <ul style="padding-left: 0;">
      <% flash[:alert].split(", ").each do |message| %>
        <li style="list-style: none;"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="header" style="background-color: #99B264;">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag "MyCropPlan_logo.png" ,size: "190x63", class: "img-fluid" %></a>
        <ul class="navbar-nav ml-auto d-flex justify-content-end">

          <% if admin_signed_in? %>
          <li class="nav-item mx-3">
            <%= link_to destroy_admin_session_path, method: :delete, style: "display:flex; align-items: center; flex-direction: column;" do %>
              <i class="fa-solid fa-right-from-bracket fa-xl" style="color: #FFD43B;"></i>
              <p class="mt-3" style="color: #FFD43B; font-size: 10px;">ログアウト</p>
            <% end %>
          </li>

          <% elsif user_signed_in? %>

          <div id="sp-menu">
            <a class="navbar-brand"><%= image_tag "MyCropPlan_whitelogo.png" ,size: "190x63", class: "img-fluid" %></a>
            <ul>
              <% unless current_user.guest_user? %>
                <li><%= link_to mypage_edit_users_path do %>アカウント設定<% end %></li>
              <% end %>
              <li><a href="/">使い方</a></li>
              <li><%= link_to plan_table_plans_path, 'data-turbolinks': false do %>カレンダー<% end %></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %>ログアウト<% end %></li>
            </ul>
          </div>

          <div id="hm-icon">
            <a class="menu-trigger" href="#">
              <span></span>
              <span></span>
              <span></span>
            </a>
          </div>

          <% else %>
            <button type="button" class="btn" data-toggle="modal" data-target="#loginModal">
              <i class="fa-solid fa-right-to-bracket fa-xl" style="color: #000;"></i>
              <p class="mt-1" style="color: #000; font-size: 10px;">ログイン</p>
            </button>
          <% end %>


        </ul>
      </div>
    </div>
  </nav>
</header>

<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel">ログイン</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "public/sessions/form", resource: resource %>
      </div>
    </div>
  </div>
</div>

<!-- Registration Modal -->
<div class="modal fade" id="registrationModal" tabindex="-1" role="dialog" aria-labelledby="registrationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="registrationModalLabel">新規登録</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "public/registrations/form", resource: resource %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCropPlan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="manifest" href="/manifest.json" crossorigin="use-credentials">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Favicon and Apple Touch Icon -->
    <%= favicon_link_tag 'MyCropPlan.ico' %>
    <%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/fccb2a51cf.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <main style="padding-bottom: 80px;">
      <div class="flash-message"><%= render 'layouts/flash' %></div>
      <%= yield %>
    </main >
    <%= render 'layouts/bottom_navbar' %>
  </body>
</html>